<a href="https://colab.research.google.com/github/Prathambiradr12345/Deep-Learning/blob/main/keras_tuner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('diabetes.csv')

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [6]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [7]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [9]:
x=scaler.fit_transform(x)

In [10]:
x.shape

(768, 8)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
import tensorflow as tf
from tensorflow import keras

In [13]:
from keras import Sequential
from keras.layers import Dense

In [14]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.fit(batch_size=32,x=x_train,y=y_train,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.4433 - loss: 0.7829 - val_accuracy: 0.6169 - val_loss: 0.7014
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5935 - loss: 0.6931 - val_accuracy: 0.7078 - val_loss: 0.6190
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6820 - loss: 0.6232 - val_accuracy: 0.7403 - val_loss: 0.5637
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7069 - loss: 0.5921 - val_accuracy: 0.7922 - val_loss: 0.5266
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6937 - loss: 0.5739 - val_accuracy: 0.7857 - val_loss: 0.5026
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7423 - loss: 0.5409 - val_accuracy: 0.8052 - val_loss: 0.4834
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7280 - loss: 0.5424 - val_accuracy: 0.8117 - val_loss: 0.4707
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7503 - loss: 0.5264 - val_accuracy: 0.8182 - val_loss: 0.4600
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7417 - loss: 0.5316 - val_accuracy: 0.8117 - val_loss: 0.4529
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5249 - val_accuracy: 0.8052 - val_loss: 0.4456
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7576 - loss: 0.5076 - val_accuracy: 0.8117 - val_loss: 0.4391
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7630 - loss: 0.4902 - val_accuracy: 0.8182 - val_loss: 0.4356
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7686 - loss: 0.4913 - val_accuracy: 0.8117 - val_loss: 0.4309
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8043 - loss: 0.4579 - val_accuracy: 0.8247 - val_loss: 0.4271
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7716 - loss: 0.4930 - val_accuracy: 0.8247 - val_loss: 0.4249
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7854 - loss: 0.4864 - val_accuracy: 0.8182 - val_loss: 0.4229
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7732 - loss: 0.4825 - val_accuracy: 0.8182 - val_loss: 0.4212
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7790 - loss: 0.4911 - val_accuracy: 0.8117 - val_loss: 0.4198
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7740 - loss: 0.4708 - val_accuracy: 0.8052 - val_loss: 0.4187
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7450 - loss: 0.4966 - val_accuracy: 0.8117 - val_loss: 0.4181
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7887 - loss: 0.4719 - val_accuracy: 0.8052 - val_loss: 0.4167
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7718 - loss: 0.4777 - val_accuracy: 0.8052 - val_loss: 0.4160
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4481 - val_accuracy: 0.7987 - val_loss: 0.4162
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7744 - loss: 0.4984 - val_accuracy: 0.7922 - val_loss: 0.4168
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8033 - loss: 0.4370 - val_accuracy: 0.7987 - val_loss: 0.4155
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7555 - loss: 0.4768 - val_accuracy: 0.8117 - val_loss: 0.4153
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7973 - loss: 0.4378 - val_accuracy: 0.7922 - val_loss: 0.4175
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7703 - loss: 0.4681 - val_accuracy: 0.7922 - val_loss: 0.4175
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7728 - loss: 0.4640 - val_accuracy: 0.7987 - val_loss: 0.4176
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7663 - loss: 0.4798 - val_accuracy: 0.7987 - val_loss: 0.4164
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7822 - loss: 0.4620 - val_accuracy: 0.8052 - val_loss: 0.4168
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7973 - loss: 0.4572 - val_accuracy: 0.8052 - val_loss: 0.4179
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7875 - loss: 0.4538 - val_accuracy: 0.8052 - val_loss: 0.4169
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7800 - loss: 0.4403 - val_accuracy: 0.8117 - val_loss: 0.4163
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7798 - loss: 0.4517 - val_accuracy: 0.8052 - val_loss: 0.4182
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7770 - loss: 0.4478 - val_accuracy: 0.8052 - val_loss: 0.4182
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7808 - loss: 0.4613 - val_accuracy: 0.8052 - val_loss: 0.4177
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7612 - loss: 0.4536 - val_accuracy: 0.8182 - val_loss: 0.4194
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8017 - loss: 0.4444 - val_accuracy: 0.8117 - val_loss: 0.4196
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7773 - loss: 0.4670 - val_accuracy: 0.8052 - val_loss: 0.4199
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7623 - loss: 0.4567 - val_accuracy: 0.8117 - val_loss: 0.4213
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4727 - val_accuracy: 0.8117 - val_loss: 0.4200
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7648 - loss: 0.4614 - val_accuracy: 0.8052 - val_loss: 0.4208
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7635 - loss: 0.4594 - val_accuracy: 0.8052 - val_loss: 0.4205
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7897 - loss: 0.4403 - val_accuracy: 0.8182 - val_loss: 0.4216
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7554 - loss: 0.4667 - val_accuracy: 0.8182 - val_loss: 0.4247
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7859 - loss: 0.4546 - val_accuracy: 0.8117 - val_loss: 0.4232
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7621 - loss: 0.4529 - val_accuracy: 0.8182 - val_loss: 0.4221
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8023 - loss: 0.4134 - val_accuracy: 0.8182 - val_loss: 0.4238
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7515 - loss: 0.4718 - val_accuracy: 0.8117 - val_loss: 0.4245
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7903 - loss: 0.4435 - val_accuracy: 0.8182 - val_loss: 0.4253
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7536 - loss: 0.4674 - val_accuracy: 0.8182 - val_loss: 0.4259
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7753 - loss: 0.4639 - val_accuracy: 0.8182 - val_loss: 0.4254
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7933 - loss: 0.4142 - val_accuracy: 0.8182 - val_loss: 0.4256
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7982 - loss: 0.4292 - val_accuracy: 0.8182 - val_loss: 0.4261
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7665 - loss: 0.4577 - val_accuracy: 0.8182 - val_loss: 0.4276
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7867 - loss: 0.4493 - val_accuracy: 0.8182 - val_loss: 0.4305
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7906 - loss: 0.4381 - val_accuracy: 0.8117 - val_loss: 0.4271
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8000 - loss: 0.4086 - val_accuracy: 0.8117 - val_loss: 0.4267
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7686 - loss: 0.4558 - val_accuracy: 0.8117 - val_loss: 0.4268
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7688 - loss: 0.4487 - val_accuracy: 0.8182 - val_loss: 0.4260
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7849 - loss: 0.4224 - val_accuracy: 0.8182 - val_loss: 0.4274
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7934 - loss: 0.4301 - val_accuracy: 0.8052 - val_loss: 0.4283
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7886 - loss: 0.4455 - val_accuracy: 0.8117 - val_loss: 0.4279
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7746 - loss: 0.4481 - val_accuracy: 0.8182 - val_loss: 0.4292
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8066 - loss: 0.4278 - val_accuracy: 0.8117 - val_loss: 0.4281
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7746 - loss: 0.4542 - val_accuracy: 0.8117 - val_loss: 0.4298
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7589 - loss: 0.4647 - val_accuracy: 0.8117 - val_loss: 0.4324
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7821 - loss: 0.4450 - val_accuracy: 0.8117 - val_loss: 0.4307
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7760 - loss: 0.4439 - val_accuracy: 0.8052 - val_loss: 0.4286
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7859 - loss: 0.4481 - val_accuracy: 0.8052 - val_loss: 0.4285
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7645 - loss: 0.4570 - val_accuracy: 0.8052 - val_loss: 0.4290
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4392 - val_accuracy: 0.7987 - val_loss: 0.4295
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8238 - loss: 0.4121 - val_accuracy: 0.7987 - val_loss: 0.4294
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8091 - loss: 0.4061 - val_accuracy: 0.7987 - val_loss: 0.4295
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8054 - loss: 0.4195 - val_accuracy: 0.8052 - val_loss: 0.4303
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7798 - loss: 0.4438 - val_accuracy: 0.7922 - val_loss: 0.4312
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7847 - loss: 0.4605 - val_accuracy: 0.8117 - val_loss: 0.4334
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4372 - val_accuracy: 0.8117 - val_loss: 0.4328
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7879 - loss: 0.4299 - val_accuracy: 0.8182 - val_loss: 0.4349
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7912 - loss: 0.4490 - val_accuracy: 0.8052 - val_loss: 0.4333
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8043 - loss: 0.4187 - val_accuracy: 0.8117 - val_loss: 0.4351
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7708 - loss: 0.4576 - val_accuracy: 0.8052 - val_loss: 0.4355
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7840 - loss: 0.4409 - val_accuracy: 0.8052 - val_loss: 0.4332
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7976 - loss: 0.4282 - val_accuracy: 0.7987 - val_loss: 0.4331
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8008 - loss: 0.4362 - val_accuracy: 0.8052 - val_loss: 0.4348
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7925 - loss: 0.4186 - val_accuracy: 0.8117 - val_loss: 0.4342
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7966 - loss: 0.4255 - val_accuracy: 0.8052 - val_loss: 0.4334
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7743 - loss: 0.4388 - val_accuracy: 0.8052 - val_loss: 0.4345
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8151 - loss: 0.4131 - val_accuracy: 0.7987 - val_loss: 0.4342
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7822 - loss: 0.4446 - val_accuracy: 0.8117 - val_loss: 0.4367
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7820 - loss: 0.4351 - val_accuracy: 0.8117 - val_loss: 0.4354
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7983 - loss: 0.4248 - val_accuracy: 0.8182 - val_loss: 0.4351
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7969 - loss: 0.4151 - val_accuracy: 0.8182 - val_loss: 0.4359
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7940 - loss: 0.4194 - val_accuracy: 0.8247 - val_loss: 0.4372
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7924 - loss: 0.4319 - val_accuracy: 0.8117 - val_loss: 0.4369
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7991 - loss: 0.4382 - val_accuracy: 0.8247 - val_loss: 0.4385
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8171 - loss: 0.4070 - val_accuracy: 0.8312 - val_loss: 0.4388
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8061 - loss: 0.4132 - val_accuracy: 0.8182 - val_loss: 0.4369
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7979 - loss: 0.4354 - val_accuracy: 0.8117 - val_loss: 0.4383

In [ ]:
#appropriate optimizer,NO.of.layer,no.of.hidden layer,all in all model

In [16]:
pip install keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.11/dist-packages (1.4.7)
Requirement already satisfied: keras in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (3.8.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (2.32.3)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (3.13.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.14.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2025.1.31)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras->keras-tuner) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [17]:
import keras_tuner as kt

In [18]:
def build_model(hp):
    model=Sequential()
    model.add(Dense(32,activation='relu',input_dim=8))
    model.add(Dense(1,activation='sigmoid'))
    model.compile(optimizer=hp.Choice('optimizer',values=['Adam','sgd','rmsprop','adadelta']),loss='binary_crossentropy',metrics=['accuracy'])
    return model

In [19]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [20]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [21]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'Adam'}

In [22]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.7653 - loss: 0.5391 - val_accuracy: 0.7987 - val_loss: 0.5179
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7529 - loss: 0.5305 - val_accuracy: 0.7857 - val_loss: 0.4978
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7614 - loss: 0.5061 - val_accuracy: 0.7987 - val_loss: 0.4828
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7863 - loss: 0.4880 - val_accuracy: 0.8182 - val_loss: 0.4713
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7647 - loss: 0.4942 - val_accuracy: 0.8182 - val_loss: 0.4627
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8010 - loss: 0.4689 - val_accuracy: 0.8247 - val_loss: 0.4575
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7855 - loss: 0.4677 - val_accuracy: 0.8182 - val_loss: 0.4522
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7778 - loss: 0.4666 - val_accuracy: 0.8247 - val_loss: 0.4471
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7903 - loss: 0.4626 - val_accuracy: 0.8182 - val_loss: 0.4445
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8074 - loss: 0.4490 - val_accuracy: 0.8247 - val_loss: 0.4417
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7901 - loss: 0.4440 - val_accuracy: 0.8182 - val_loss: 0.4394
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7642 - loss: 0.4670 - val_accuracy: 0.8182 - val_loss: 0.4379
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7652 - loss: 0.4879 - val_accuracy: 0.8052 - val_loss: 0.4354
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7731 - loss: 0.4586 - val_accuracy: 0.8182 - val_loss: 0.4340
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7884 - loss: 0.4413 - val_accuracy: 0.8247 - val_loss: 0.4334
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7808 - loss: 0.4571 - val_accuracy: 0.8182 - val_loss: 0.4311
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7859 - loss: 0.4567 - val_accuracy: 0.8117 - val_loss: 0.4316
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7700 - loss: 0.4545 - val_accuracy: 0.8117 - val_loss: 0.4334
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8023 - loss: 0.4332 - val_accuracy: 0.8052 - val_loss: 0.4338
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7792 - loss: 0.4576 - val_accuracy: 0.7987 - val_loss: 0.4331
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7584 - loss: 0.4702 - val_accuracy: 0.7987 - val_loss: 0.4325
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7794 - loss: 0.4615 - val_accuracy: 0.8052 - val_loss: 0.4330
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7941 - loss: 0.4238 - val_accuracy: 0.8117 - val_loss: 0.4330
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8010 - loss: 0.4424 - val_accuracy: 0.8182 - val_loss: 0.4334
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8202 - loss: 0.4059 - val_accuracy: 0.8182 - val_loss: 0.4325
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7970 - loss: 0.4317 - val_accuracy: 0.8247 - val_loss: 0.4345
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7875 - loss: 0.4322 - val_accuracy: 0.8247 - val_loss: 0.4358
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7828 - loss: 0.4456 - val_accuracy: 0.8182 - val_loss: 0.4355
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8057 - loss: 0.4300 - val_accuracy: 0.8182 - val_loss: 0.4344
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7938 - loss: 0.4407 - val_accuracy: 0.8182 - val_loss: 0.4347
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8073 - loss: 0.4220 - val_accuracy: 0.8182 - val_loss: 0.4346
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8044 - loss: 0.4211 - val_accuracy: 0.8182 - val_loss: 0.4346
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7963 - loss: 0.4469 - val_accuracy: 0.8182 - val_loss: 0.4342
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7826 - loss: 0.4552 - val_accuracy: 0.8182 - val_loss: 0.4341
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7885 - loss: 0.4412 - val_accuracy: 0.8182 - val_loss: 0.4348
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7816 - loss: 0.4403 - val_accuracy: 0.8182 - val_loss: 0.4350
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8006 - loss: 0.4365 - val_accuracy: 0.8247 - val_loss: 0.4360
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7982 - loss: 0.4275 - val_accuracy: 0.8247 - val_loss: 0.4350
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8114 - loss: 0.4252 - val_accuracy: 0.8247 - val_loss: 0.4362
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8112 - loss: 0.4223 - val_accuracy: 0.8312 - val_loss: 0.4376
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7922 - loss: 0.4254 - val_accuracy: 0.8312 - val_loss: 0.4354
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.7896 - loss: 0.4297 - val_accuracy: 0.8312 - val_loss: 0.4348
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8158 - loss: 0.4121 - val_accuracy: 0.8247 - val_loss: 0.4339
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7975 - loss: 0.4199 - val_accuracy: 0.8247 - val_loss: 0.4371
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8100 - loss: 0.4087 - val_accuracy: 0.8247 - val_loss: 0.4373
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7769 - loss: 0.4458 - val_accuracy: 0.8247 - val_loss: 0.4364
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8041 - loss: 0.4159 - val_accuracy: 0.8247 - val_loss: 0.4391
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8170 - loss: 0.4127 - val_accuracy: 0.8182 - val_loss: 0.4386
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7939 - loss: 0.4267 - val_accuracy: 0.8182 - val_loss: 0.4371
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7902 - loss: 0.4380 - val_accuracy: 0.8182 - val_loss: 0.4406
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4219 - val_accuracy: 0.8182 - val_loss: 0.4412
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8190 - loss: 0.4089 - val_accuracy: 0.8182 - val_loss: 0.4387
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8099 - loss: 0.4347 - val_accuracy: 0.8182 - val_loss: 0.4403
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8014 - loss: 0.4241 - val_accuracy: 0.8182 - val_loss: 0.4422
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8059 - loss: 0.4231 - val_accuracy: 0.8182 - val_loss: 0.4426
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7898 - loss: 0.4260 - val_accuracy: 0.8247 - val_loss: 0.4424
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8024 - loss: 0.4244 - val_accuracy: 0.8117 - val_loss: 0.4391
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8047 - loss: 0.4267 - val_accuracy: 0.8247 - val_loss: 0.4409
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8180 - loss: 0.3979 - val_accuracy: 0.8247 - val_loss: 0.4407
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7942 - loss: 0.4281 - val_accuracy: 0.8247 - val_loss: 0.4414
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7815 - loss: 0.4459 - val_accuracy: 0.8182 - val_loss: 0.4420
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7924 - loss: 0.4225 - val_accuracy: 0.8182 - val_loss: 0.4411
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7956 - loss: 0.4178 - val_accuracy: 0.8182 - val_loss: 0.4414
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7991 - loss: 0.4132 - val_accuracy: 0.8117 - val_loss: 0.4406
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7893 - loss: 0.4433 - val_accuracy: 0.8247 - val_loss: 0.4426
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7663 - loss: 0.4618 - val_accuracy: 0.8117 - val_loss: 0.4423
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4247 - val_accuracy: 0.8182 - val_loss: 0.4432
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8195 - loss: 0.3890 - val_accuracy: 0.8117 - val_loss: 0.4429
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7995 - loss: 0.4209 - val_accuracy: 0.8117 - val_loss: 0.4440
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8124 - loss: 0.4318 - val_accuracy: 0.8182 - val_loss: 0.4453
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8067 - loss: 0.4314 - val_accuracy: 0.8117 - val_loss: 0.4457
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8041 - loss: 0.4124 - val_accuracy: 0.8247 - val_loss: 0.4438
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8175 - loss: 0.4027 - val_accuracy: 0.8247 - val_loss: 0.4443
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8080 - loss: 0.4109 - val_accuracy: 0.8117 - val_loss: 0.4449
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8100 - loss: 0.4138 - val_accuracy: 0.8182 - val_loss: 0.4452
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8199 - loss: 0.4085 - val_accuracy: 0.8182 - val_loss: 0.4432
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7913 - loss: 0.4399 - val_accuracy: 0.8052 - val_loss: 0.4447
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7981 - loss: 0.4249 - val_accuracy: 0.8052 - val_loss: 0.4434
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7829 - loss: 0.4537 - val_accuracy: 0.8117 - val_loss: 0.4435
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8051 - loss: 0.4071 - val_accuracy: 0.8117 - val_loss: 0.4450
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8169 - loss: 0.4046 - val_accuracy: 0.8182 - val_loss: 0.4459
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8071 - loss: 0.4090 - val_accuracy: 0.8182 - val_loss: 0.4472
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4266 - val_accuracy: 0.8312 - val_loss: 0.4474
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7852 - loss: 0.4234 - val_accuracy: 0.8312 - val_loss: 0.4487
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8083 - loss: 0.4118 - val_accuracy: 0.8117 - val_loss: 0.4469
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8009 - loss: 0.4417 - val_accuracy: 0.8117 - val_loss: 0.4494
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8159 - loss: 0.4126 - val_accuracy: 0.8117 - val_loss: 0.4472
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8032 - loss: 0.4217 - val_accuracy: 0.8182 - val_loss: 0.4480
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8182 - loss: 0.3982 - val_accuracy: 0.8117 - val_loss: 0.4485
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8009 - loss: 0.4185 - val_accuracy: 0.8117 - val_loss: 0.4479
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8341 - loss: 0.3741 - val_accuracy: 0.8117 - val_loss: 0.4470
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4110 - val_accuracy: 0.8117 - val_loss: 0.4497
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8015 - loss: 0.4344 - val_accuracy: 0.8117 - val_loss: 0.4470
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8246 - loss: 0.3920 - val_accuracy: 0.8117 - val_loss: 0.4488

In [25]:
def build_model(hp):
    model=Sequential()
    units=hp.Int('units',min_value=8,max_value=128)
    model.add(Dense(units=units,activation='relu',input_dim=8))
    # Corrected line: Add a Dense layer with 1 unit and sigmoid activation
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer=hp.Choice('optimizer',values=['Adam','sgd','rmsprop','adadelta']),loss='binary_crossentropy',metrics=['accuracy'])
    return model

In [26]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=None,directory="mydir")

Reloading Tuner from mydir/untitled_project/tuner0.json

In [27]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [28]:
tuner.get_best_hyperparameters()[0].values

{'units': 120, 'optimizer': 'rmsprop'}

In [29]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [30]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7671 - loss: 0.4951 - val_accuracy: 0.8182 - val_loss: 0.4322
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7717 - loss: 0.4830 - val_accuracy: 0.8117 - val_loss: 0.4289
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7691 - loss: 0.4788 - val_accuracy: 0.8052 - val_loss: 0.4255
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7680 - loss: 0.4670 - val_accuracy: 0.8182 - val_loss: 0.4236
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7682 - loss: 0.4634 - val_accuracy: 0.8247 - val_loss: 0.4239
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7705 - loss: 0.4720 - val_accuracy: 0.8247 - val_loss: 0.4228
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7641 - loss: 0.4504 - val_accuracy: 0.8247 - val_loss: 0.4231
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7766 - loss: 0.4514 - val_accuracy: 0.8247 - val_loss: 0.4211
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7280 - loss: 0.4967 - val_accuracy: 0.8182 - val_loss: 0.4211
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7821 - loss: 0.4429 - val_accuracy: 0.8182 - val_loss: 0.4218
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7580 - loss: 0.4703 - val_accuracy: 0.8312 - val_loss: 0.4222
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7900 - loss: 0.4285 - val_accuracy: 0.8182 - val_loss: 0.4237
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7965 - loss: 0.4443 - val_accuracy: 0.8247 - val_loss: 0.4223
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7737 - loss: 0.4319 - val_accuracy: 0.8312 - val_loss: 0.4237
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7632 - loss: 0.4550 - val_accuracy: 0.8117 - val_loss: 0.4270
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7881 - loss: 0.4498 - val_accuracy: 0.8117 - val_loss: 0.4274
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7679 - loss: 0.4518 - val_accuracy: 0.8052 - val_loss: 0.4291
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7912 - loss: 0.4305 - val_accuracy: 0.8117 - val_loss: 0.4257
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7631 - loss: 0.4533 - val_accuracy: 0.8052 - val_loss: 0.4297
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7978 - loss: 0.4373 - val_accuracy: 0.8052 - val_loss: 0.4283
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8039 - loss: 0.4239 - val_accuracy: 0.8117 - val_loss: 0.4334
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7774 - loss: 0.4461 - val_accuracy: 0.8117 - val_loss: 0.4332
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7734 - loss: 0.4593 - val_accuracy: 0.8117 - val_loss: 0.4303
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7813 - loss: 0.4529 - val_accuracy: 0.8182 - val_loss: 0.4305
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7853 - loss: 0.4491 - val_accuracy: 0.8182 - val_loss: 0.4299
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4349 - val_accuracy: 0.8117 - val_loss: 0.4313
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7720 - loss: 0.4562 - val_accuracy: 0.8117 - val_loss: 0.4350
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7968 - loss: 0.4353 - val_accuracy: 0.8117 - val_loss: 0.4342
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7992 - loss: 0.4243 - val_accuracy: 0.8117 - val_loss: 0.4341
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7968 - loss: 0.4137 - val_accuracy: 0.8182 - val_loss: 0.4366
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8009 - loss: 0.4226 - val_accuracy: 0.8117 - val_loss: 0.4364
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7885 - loss: 0.4269 - val_accuracy: 0.8182 - val_loss: 0.4414
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7840 - loss: 0.4224 - val_accuracy: 0.8052 - val_loss: 0.4449
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8108 - loss: 0.4030 - val_accuracy: 0.8182 - val_loss: 0.4416
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8119 - loss: 0.4162 - val_accuracy: 0.8182 - val_loss: 0.4462
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8182 - loss: 0.4188 - val_accuracy: 0.8182 - val_loss: 0.4444
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7958 - loss: 0.4391 - val_accuracy: 0.8117 - val_loss: 0.4487
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8227 - loss: 0.4213 - val_accuracy: 0.8182 - val_loss: 0.4453
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8018 - loss: 0.4314 - val_accuracy: 0.8182 - val_loss: 0.4425
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4101 - val_accuracy: 0.8182 - val_loss: 0.4459
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7881 - loss: 0.4319 - val_accuracy: 0.8117 - val_loss: 0.4469
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8218 - loss: 0.3837 - val_accuracy: 0.8247 - val_loss: 0.4439
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8159 - loss: 0.3970 - val_accuracy: 0.8247 - val_loss: 0.4458
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8041 - loss: 0.4017 - val_accuracy: 0.8247 - val_loss: 0.4477
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3934 - val_accuracy: 0.8312 - val_loss: 0.4468
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8248 - loss: 0.4033 - val_accuracy: 0.8312 - val_loss: 0.4481
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8217 - loss: 0.3995 - val_accuracy: 0.8312 - val_loss: 0.4463
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8309 - loss: 0.3940 - val_accuracy: 0.8247 - val_loss: 0.4491
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7967 - loss: 0.4280 - val_accuracy: 0.8312 - val_loss: 0.4459
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8199 - loss: 0.4158 - val_accuracy: 0.8182 - val_loss: 0.4514
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8151 - loss: 0.4200 - val_accuracy: 0.8247 - val_loss: 0.4501
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8365 - loss: 0.4002 - val_accuracy: 0.8182 - val_loss: 0.4481
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8121 - loss: 0.4120 - val_accuracy: 0.8182 - val_loss: 0.4495
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8196 - loss: 0.4126 - val_accuracy: 0.8182 - val_loss: 0.4475
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8249 - loss: 0.3928 - val_accuracy: 0.8182 - val_loss: 0.4484
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8281 - loss: 0.3927 - val_accuracy: 0.8182 - val_loss: 0.4535
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8132 - loss: 0.4044 - val_accuracy: 0.8247 - val_loss: 0.4522
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8082 - loss: 0.3949 - val_accuracy: 0.8182 - val_loss: 0.4532
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8424 - loss: 0.3702 - val_accuracy: 0.8182 - val_loss: 0.4534
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8261 - loss: 0.3973 - val_accuracy: 0.8117 - val_loss: 0.4560
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8271 - loss: 0.3969 - val_accuracy: 0.8182 - val_loss: 0.4546
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8097 - loss: 0.4038 - val_accuracy: 0.8182 - val_loss: 0.4549
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8170 - loss: 0.4085 - val_accuracy: 0.8247 - val_loss: 0.4503
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8341 - loss: 0.3725 - val_accuracy: 0.8182 - val_loss: 0.4540
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4283 - val_accuracy: 0.8247 - val_loss: 0.4548
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8173 - loss: 0.3933 - val_accuracy: 0.8247 - val_loss: 0.4524
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8163 - loss: 0.4063 - val_accuracy: 0.8247 - val_loss: 0.4524
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8202 - loss: 0.3996 - val_accuracy: 0.8247 - val_loss: 0.4545
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8218 - loss: 0.3969 - val_accuracy: 0.8247 - val_loss: 0.4572
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8090 - loss: 0.4135 - val_accuracy: 0.8247 - val_loss: 0.4581
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8006 - loss: 0.4008 - val_accuracy: 0.8117 - val_loss: 0.4522
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8234 - loss: 0.4031 - val_accuracy: 0.8247 - val_loss: 0.4534
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8155 - loss: 0.4041 - val_accuracy: 0.8117 - val_loss: 0.4555
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8155 - loss: 0.3918 - val_accuracy: 0.8312 - val_loss: 0.4574
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7902 - loss: 0.4348 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8135 - loss: 0.3971 - val_accuracy: 0.8247 - val_loss: 0.4521
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8218 - loss: 0.3977 - val_accuracy: 0.8247 - val_loss: 0.4507
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8224 - loss: 0.3961 - val_accuracy: 0.8182 - val_loss: 0.4509
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8156 - loss: 0.4159 - val_accuracy: 0.8247 - val_loss: 0.4565
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8131 - loss: 0.3931 - val_accuracy: 0.8247 - val_loss: 0.4569
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8496 - loss: 0.3778 - val_accuracy: 0.8247 - val_loss: 0.4601
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8383 - loss: 0.3898 - val_accuracy: 0.8247 - val_loss: 0.4629
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8267 - loss: 0.3954 - val_accuracy: 0.8247 - val_loss: 0.4585
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8009 - loss: 0.4128 - val_accuracy: 0.8247 - val_loss: 0.4564
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8141 - loss: 0.4231 - val_accuracy: 0.8247 - val_loss: 0.4605
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8200 - loss: 0.3874 - val_accuracy: 0.8247 - val_loss: 0.4586
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8163 - loss: 0.4120 - val_accuracy: 0.8247 - val_loss: 0.4573
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3859 - val_accuracy: 0.8247 - val_loss: 0.4590
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8190 - loss: 0.4022 - val_accuracy: 0.8247 - val_loss: 0.4609
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8432 - loss: 0.3643 - val_accuracy: 0.8182 - val_loss: 0.4665
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8368 - loss: 0.3937 - val_accuracy: 0.8247 - val_loss: 0.4632
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3888 - val_accuracy: 0.8247 - val_loss: 0.4680
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8219 - loss: 0.3870 - val_accuracy: 0.8117 - val_loss: 0.4764
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8167 - loss: 0.4026 - val_accuracy: 0.8247 - val_loss: 0.4668

In [31]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(72,activation='relu',input_dim=8))
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(72,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['Adam','sgd','rmsprop','adadelta']),loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [32]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=None,directory="mydir",project_name='diabetes')

Reloading Tuner from mydir/diabetes/tuner0.json

In [33]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [35]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3, 'optimizer': 'rmsprop'}

In [34]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 12 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [36]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.7642 - loss: 0.4909 - val_accuracy: 0.8052 - val_loss: 0.4309
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8015 - loss: 0.4142 - val_accuracy: 0.7987 - val_loss: 0.4361
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8115 - loss: 0.4247 - val_accuracy: 0.7792 - val_loss: 0.4656
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7907 - loss: 0.4092 - val_accuracy: 0.7922 - val_loss: 0.4402
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8199 - loss: 0.4021 - val_accuracy: 0.8052 - val_loss: 0.4460
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8075 - loss: 0.4105 - val_accuracy: 0.8117 - val_loss: 0.4823
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8298 - loss: 0.3840 - val_accuracy: 0.7727 - val_loss: 0.4711
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8262 - loss: 0.3922 - val_accuracy: 0.7857 - val_loss: 0.4948
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8261 - loss: 0.3859 - val_accuracy: 0.7922 - val_loss: 0.4797
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8419 - loss: 0.3489 - val_accuracy: 0.7857 - val_loss: 0.4732
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8384 - loss: 0.3426 - val_accuracy: 0.7857 - val_loss: 0.4845
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8696 - loss: 0.3317 - val_accuracy: 0.7792 - val_loss: 0.4873
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3377 - val_accuracy: 0.7857 - val_loss: 0.5062
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8498 - loss: 0.3290 - val_accuracy: 0.7727 - val_loss: 0.5417
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8491 - loss: 0.3151 - val_accuracy: 0.7857 - val_loss: 0.5108
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8402 - loss: 0.3311 - val_accuracy: 0.8052 - val_loss: 0.5186
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8695 - loss: 0.3131 - val_accuracy: 0.7727 - val_loss: 0.5150
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3149 - val_accuracy: 0.7468 - val_loss: 0.6363
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3101 - val_accuracy: 0.7597 - val_loss: 0.6145
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8504 - loss: 0.3455 - val_accuracy: 0.8182 - val_loss: 0.5700
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8710 - loss: 0.3056 - val_accuracy: 0.7987 - val_loss: 0.5572
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.2738 - val_accuracy: 0.7662 - val_loss: 0.6037
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8882 - loss: 0.2843 - val_accuracy: 0.7208 - val_loss: 0.7084
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8983 - loss: 0.2483 - val_accuracy: 0.7727 - val_loss: 0.6214
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8923 - loss: 0.2644 - val_accuracy: 0.7857 - val_loss: 0.6013
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8896 - loss: 0.2495 - val_accuracy: 0.7273 - val_loss: 0.6754
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9184 - loss: 0.2446 - val_accuracy: 0.7403 - val_loss: 0.6271
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9100 - loss: 0.2300 - val_accuracy: 0.7727 - val_loss: 0.6267
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9011 - loss: 0.2417 - val_accuracy: 0.7532 - val_loss: 0.6323
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9255 - loss: 0.2297 - val_accuracy: 0.7597 - val_loss: 0.6632
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9186 - loss: 0.2072 - val_accuracy: 0.7078 - val_loss: 0.7739
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9406 - loss: 0.1985 - val_accuracy: 0.7143 - val_loss: 0.8418
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9347 - loss: 0.1883 - val_accuracy: 0.7468 - val_loss: 0.7828
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9201 - loss: 0.1841 - val_accuracy: 0.7403 - val_loss: 0.7843
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9320 - loss: 0.2034 - val_accuracy: 0.7273 - val_loss: 0.8371
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9573 - loss: 0.1708 - val_accuracy: 0.7273 - val_loss: 0.9051
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9395 - loss: 0.1726 - val_accuracy: 0.7597 - val_loss: 0.8118
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9337 - loss: 0.1587 - val_accuracy: 0.7727 - val_loss: 0.8056
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9409 - loss: 0.1478 - val_accuracy: 0.7403 - val_loss: 0.9033
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9500 - loss: 0.1486 - val_accuracy: 0.7662 - val_loss: 0.8778
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9415 - loss: 0.1737 - val_accuracy: 0.7468 - val_loss: 0.8739
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9444 - loss: 0.1399 - val_accuracy: 0.7468 - val_loss: 0.9799
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9472 - loss: 0.1466 - val_accuracy: 0.7143 - val_loss: 1.0173
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9586 - loss: 0.1303 - val_accuracy: 0.7792 - val_loss: 0.9241
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9459 - loss: 0.1405 - val_accuracy: 0.7403 - val_loss: 1.0208
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9497 - loss: 0.1260 - val_accuracy: 0.7273 - val_loss: 1.0226
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9598 - loss: 0.1354 - val_accuracy: 0.7338 - val_loss: 0.9939
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9706 - loss: 0.1024 - val_accuracy: 0.6818 - val_loss: 1.3583
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9304 - loss: 0.1829 - val_accuracy: 0.7468 - val_loss: 1.0757
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9652 - loss: 0.0954 - val_accuracy: 0.7662 - val_loss: 1.0557
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9509 - loss: 0.1225 - val_accuracy: 0.7468 - val_loss: 1.0750
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9596 - loss: 0.1053 - val_accuracy: 0.7468 - val_loss: 1.1866
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9624 - loss: 0.0938 - val_accuracy: 0.7532 - val_loss: 1.1052
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9568 - loss: 0.1017 - val_accuracy: 0.7403 - val_loss: 1.1331
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9613 - loss: 0.1032 - val_accuracy: 0.7338 - val_loss: 1.1713
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9695 - loss: 0.0865 - val_accuracy: 0.7597 - val_loss: 1.2875
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9590 - loss: 0.1113 - val_accuracy: 0.7468 - val_loss: 1.2673
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9717 - loss: 0.0885 - val_accuracy: 0.7468 - val_loss: 1.2927
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9794 - loss: 0.0585 - val_accuracy: 0.7338 - val_loss: 1.2718
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9915 - loss: 0.0565 - val_accuracy: 0.6169 - val_loss: 1.6265
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9649 - loss: 0.0788 - val_accuracy: 0.7143 - val_loss: 1.3706
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9680 - loss: 0.0696 - val_accuracy: 0.7273 - val_loss: 1.3465
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0643 - val_accuracy: 0.7338 - val_loss: 1.3505
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9748 - loss: 0.0788 - val_accuracy: 0.7468 - val_loss: 1.4100
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9817 - loss: 0.0521 - val_accuracy: 0.6883 - val_loss: 1.6102
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9699 - loss: 0.0773 - val_accuracy: 0.7273 - val_loss: 1.4431
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0402 - val_accuracy: 0.6948 - val_loss: 1.7155
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9653 - loss: 0.0679 - val_accuracy: 0.7143 - val_loss: 1.5167
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9887 - loss: 0.0532 - val_accuracy: 0.7532 - val_loss: 1.5175
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9917 - loss: 0.0442 - val_accuracy: 0.7013 - val_loss: 1.5390
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9973 - loss: 0.0344 - val_accuracy: 0.7403 - val_loss: 1.6063
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9872 - loss: 0.0417 - val_accuracy: 0.7532 - val_loss: 1.7673
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9712 - loss: 0.1133 - val_accuracy: 0.7338 - val_loss: 1.6783
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9863 - loss: 0.0488 - val_accuracy: 0.7468 - val_loss: 1.6800
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9929 - loss: 0.0339 - val_accuracy: 0.7273 - val_loss: 1.8153
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9695 - loss: 0.0660 - val_accuracy: 0.7468 - val_loss: 1.7423
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9980 - loss: 0.0181 - val_accuracy: 0.7468 - val_loss: 1.6410
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9920 - loss: 0.0265 - val_accuracy: 0.7597 - val_loss: 1.7042
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9868 - loss: 0.0329 - val_accuracy: 0.7468 - val_loss: 1.7972
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9752 - loss: 0.0572 - val_accuracy: 0.7078 - val_loss: 1.8244
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9973 - loss: 0.0266 - val_accuracy: 0.7143 - val_loss: 1.8643
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9862 - loss: 0.0366 - val_accuracy: 0.7468 - val_loss: 1.8607
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9944 - loss: 0.0277 - val_accuracy: 0.7013 - val_loss: 1.9392
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9795 - loss: 0.0673 - val_accuracy: 0.7468 - val_loss: 1.9501
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9749 - loss: 0.0614 - val_accuracy: 0.7208 - val_loss: 2.0013
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9954 - loss: 0.0149 - val_accuracy: 0.7273 - val_loss: 2.1608
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9845 - loss: 0.0534 - val_accuracy: 0.7403 - val_loss: 2.0441
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9956 - loss: 0.0147 - val_accuracy: 0.7338 - val_loss: 2.0612
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9929 - loss: 0.0185 - val_accuracy: 0.7532 - val_loss: 2.0615
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9888 - loss: 0.0340 - val_accuracy: 0.7273 - val_loss: 2.1470
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9988 - loss: 0.0108 - val_accuracy: 0.7403 - val_loss: 2.1214
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9869 - loss: 0.0271 - val_accuracy: 0.7403 - val_loss: 2.1621
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9989 - loss: 0.0119 - val_accuracy: 0.7468 - val_loss: 2.1816
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9840 - loss: 0.0477 - val_accuracy: 0.7597 - val_loss: 2.1903

In [45]:
def build_model(hp):
  model=Sequential()

  c=0
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    if c==0:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=120,strp=8),activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid']),input_dim=8))
    else:
       model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=120,strp=8),activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid'])))
    c+=1
    model.add(Dense(1,activation='sigmoid'))
    model.compile(optimizer=hp.Choice('optimizer',values=['Adam','sgd','rmsprop','adadelta']),loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [46]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=None,directory="mydir",project_name='final')

Reloading Tuner from mydir/final/tuner0.json

In [47]:
def build_model(hp):
    model = Sequential()

    c = 0
    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        if c == 0:
            # Corrected line: Change 'strp' to 'step'
            model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=120, step=8),
                            activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
                            input_dim=8))
        else:
            # Corrected line: Change 'strp' to 'step'
            model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=120, step=8),
                            activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])))
        c += 1
    # Corrected line: Moved outside the loop to add the output layer only once
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer=hp.Choice('optimizer', values=['Adam', 'sgd', 'rmsprop', 'adadelta']),
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

In [48]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=None,directory="mydir",project_name='final')

Reloading Tuner from mydir/final/tuner0.json

In [51]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 72,
 'activation0': 'relu',
 'optimizer': 'rmsprop',
 'units1': 88,
 'activation1': 'tanh',
 'units2': 24,
 'activation2': 'relu',
 'units3': 88,
 'activation3': 'sigmoid',
 'units4': 64,
 'activation4': 'relu',
 'units5': 88,
 'activation5': 'tanh',
 'units6': 24,
 'activation6': 'relu',
 'units7': 104,
 'activation7': 'tanh',
 'units8': 112,
 'activation8': 'relu',
 'units9': 48,
 'activation9': 'sigmoid'}

In [52]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [53]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7715 - loss: 0.4622 - val_accuracy: 0.8117 - val_loss: 0.4248
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7905 - loss: 0.4332 - val_accuracy: 0.7922 - val_loss: 0.4487
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7851 - loss: 0.4432 - val_accuracy: 0.8052 - val_loss: 0.4239
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7852 - loss: 0.4319 - val_accuracy: 0.8052 - val_loss: 0.4218
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8067 - loss: 0.4346 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4257 - val_accuracy: 0.8052 - val_loss: 0.4254
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4159 - val_accuracy: 0.7922 - val_loss: 0.4339
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7809 - loss: 0.4324 - val_accuracy: 0.8052 - val_loss: 0.4408
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8036 - loss: 0.4243 - val_accuracy: 0.8182 - val_loss: 0.4290
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8224 - loss: 0.3949 - val_accuracy: 0.7922 - val_loss: 0.4282
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7608 - loss: 0.4708 - val_accuracy: 0.8182 - val_loss: 0.4299
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7885 - loss: 0.4303 - val_accuracy: 0.8182 - val_loss: 0.4389
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7956 - loss: 0.4454 - val_accuracy: 0.7987 - val_loss: 0.4319
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4573 - val_accuracy: 0.8182 - val_loss: 0.4339
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7898 - loss: 0.4200 - val_accuracy: 0.8247 - val_loss: 0.4359
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8184 - loss: 0.3924 - val_accuracy: 0.7987 - val_loss: 0.4578
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8231 - loss: 0.4270 - val_accuracy: 0.8117 - val_loss: 0.4546
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8115 - loss: 0.3941 - val_accuracy: 0.7727 - val_loss: 0.4777
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4291 - val_accuracy: 0.8182 - val_loss: 0.4472
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4155 - val_accuracy: 0.8117 - val_loss: 0.4450
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8058 - loss: 0.4149 - val_accuracy: 0.7987 - val_loss: 0.4731
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7940 - loss: 0.4240 - val_accuracy: 0.8117 - val_loss: 0.4559
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8023 - loss: 0.4126 - val_accuracy: 0.8052 - val_loss: 0.4444
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8240 - loss: 0.3859 - val_accuracy: 0.8052 - val_loss: 0.4523
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7933 - loss: 0.4439 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8051 - loss: 0.3943 - val_accuracy: 0.8247 - val_loss: 0.4590
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8289 - loss: 0.3875 - val_accuracy: 0.7987 - val_loss: 0.4743
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8209 - loss: 0.3801 - val_accuracy: 0.8247 - val_loss: 0.4714
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7998 - loss: 0.3965 - val_accuracy: 0.8182 - val_loss: 0.4652
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8284 - loss: 0.3957 - val_accuracy: 0.7792 - val_loss: 0.5005
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8449 - loss: 0.3760 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.3913 - val_accuracy: 0.8182 - val_loss: 0.4604
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8178 - loss: 0.3749 - val_accuracy: 0.8182 - val_loss: 0.4656
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3956 - val_accuracy: 0.7857 - val_loss: 0.4931
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8272 - loss: 0.3857 - val_accuracy: 0.8182 - val_loss: 0.4666
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3872 - val_accuracy: 0.8052 - val_loss: 0.4946
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8219 - loss: 0.3964 - val_accuracy: 0.8247 - val_loss: 0.4668
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7925 - loss: 0.3884 - val_accuracy: 0.7727 - val_loss: 0.4624
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8370 - loss: 0.3776 - val_accuracy: 0.7857 - val_loss: 0.4701
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8476 - loss: 0.3609 - val_accuracy: 0.8117 - val_loss: 0.4838
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8360 - loss: 0.3785 - val_accuracy: 0.7532 - val_loss: 0.4742
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8161 - loss: 0.4132 - val_accuracy: 0.7987 - val_loss: 0.4704
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8087 - loss: 0.3946 - val_accuracy: 0.7857 - val_loss: 0.5110
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8323 - loss: 0.3758 - val_accuracy: 0.7792 - val_loss: 0.5115
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3885 - val_accuracy: 0.7987 - val_loss: 0.4757
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8099 - loss: 0.3962 - val_accuracy: 0.8182 - val_loss: 0.4867
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8253 - loss: 0.3845 - val_accuracy: 0.7727 - val_loss: 0.5230
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.3533 - val_accuracy: 0.7922 - val_loss: 0.5046
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8073 - loss: 0.3800 - val_accuracy: 0.7857 - val_loss: 0.5066
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8394 - loss: 0.3795 - val_accuracy: 0.8052 - val_loss: 0.4965
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8492 - loss: 0.3464 - val_accuracy: 0.8117 - val_loss: 0.4813
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8255 - loss: 0.3876 - val_accuracy: 0.8182 - val_loss: 0.4760
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8540 - loss: 0.3342 - val_accuracy: 0.7857 - val_loss: 0.5183
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8461 - loss: 0.3524 - val_accuracy: 0.8182 - val_loss: 0.4812
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8155 - loss: 0.3822 - val_accuracy: 0.8312 - val_loss: 0.4858
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8307 - loss: 0.3735 - val_accuracy: 0.7857 - val_loss: 0.4766
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8337 - loss: 0.3662 - val_accuracy: 0.8117 - val_loss: 0.4859
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8363 - loss: 0.3452 - val_accuracy: 0.7987 - val_loss: 0.4849
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8376 - loss: 0.3532 - val_accuracy: 0.7857 - val_loss: 0.5076
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8475 - loss: 0.3457 - val_accuracy: 0.7922 - val_loss: 0.5152
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8519 - loss: 0.3554 - val_accuracy: 0.7922 - val_loss: 0.4863
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8748 - loss: 0.3229 - val_accuracy: 0.7662 - val_loss: 0.5128
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8392 - loss: 0.3474 - val_accuracy: 0.7727 - val_loss: 0.5210
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8580 - loss: 0.3396 - val_accuracy: 0.7857 - val_loss: 0.5606
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3661 - val_accuracy: 0.8182 - val_loss: 0.5086
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8492 - loss: 0.3603 - val_accuracy: 0.7922 - val_loss: 0.5258
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8632 - loss: 0.3269 - val_accuracy: 0.7922 - val_loss: 0.5182
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8450 - loss: 0.3402 - val_accuracy: 0.7922 - val_loss: 0.5115
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8770 - loss: 0.3206 - val_accuracy: 0.7727 - val_loss: 0.5304
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8627 - loss: 0.3324 - val_accuracy: 0.7662 - val_loss: 0.5466
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8425 - loss: 0.3486 - val_accuracy: 0.7922 - val_loss: 0.5150
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8545 - loss: 0.3288 - val_accuracy: 0.7727 - val_loss: 0.5469
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8529 - loss: 0.3416 - val_accuracy: 0.7922 - val_loss: 0.5357
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8556 - loss: 0.3396 - val_accuracy: 0.8052 - val_loss: 0.5024
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8455 - loss: 0.3445 - val_accuracy: 0.7857 - val_loss: 0.5616
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8701 - loss: 0.3370 - val_accuracy: 0.7792 - val_loss: 0.5421
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8647 - loss: 0.3312 - val_accuracy: 0.7727 - val_loss: 0.5644
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8390 - loss: 0.3572 - val_accuracy: 0.7532 - val_loss: 0.5467
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8647 - loss: 0.3224 - val_accuracy: 0.7662 - val_loss: 0.5448
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8700 - loss: 0.3091 - val_accuracy: 0.7987 - val_loss: 0.5224
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8709 - loss: 0.3175 - val_accuracy: 0.7403 - val_loss: 0.5735
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8682 - loss: 0.3050 - val_accuracy: 0.7532 - val_loss: 0.5457
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8615 - loss: 0.3093 - val_accuracy: 0.7792 - val_loss: 0.5623
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8582 - loss: 0.3274 - val_accuracy: 0.7662 - val_loss: 0.5464
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8685 - loss: 0.3089 - val_accuracy: 0.8052 - val_loss: 0.5460
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8626 - loss: 0.3079 - val_accuracy: 0.7857 - val_loss: 0.5696
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8939 - loss: 0.2850 - val_accuracy: 0.7532 - val_loss: 0.5281
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8643 - loss: 0.3134 - val_accuracy: 0.7532 - val_loss: 0.5708
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8734 - loss: 0.3087 - val_accuracy: 0.8052 - val_loss: 0.5523
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3367 - val_accuracy: 0.7857 - val_loss: 0.5788
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8597 - loss: 0.3044 - val_accuracy: 0.7662 - val_loss: 0.6150
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8808 - loss: 0.3004 - val_accuracy: 0.7792 - val_loss: 0.5787
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8644 - loss: 0.3076 - val_accuracy: 0.7662 - val_loss: 0.5581
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8860 - loss: 0.2902 - val_accuracy: 0.7727 - val_loss: 0.5570